[package]
name = "kvapp"
version = "0.1.0"
authors = ["jgarzik"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "^0.4"

